version: '3.8'

services:
  app:
    build: .
    container_name: b2c-payment-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
    depends_on:
      - db

  db:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - "9092:9092"
